openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://apiies.test'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/lists/categories:
    get:
      summary: ''
      operationId: getApiListsCategories
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'updated category from API'
                    -
                      id: 2
                      name: 'expedita aut quos'
                    -
                      id: 3
                      name: 'voluptas corporis nihil'
                    -
                      id: 4
                      name: 'eum eius velit'
                    -
                      id: 5
                      name: 'impedit maxime aliquam'
                    -
                      id: 6
                      name: 'vel voluptatibus odio'
                    -
                      id: 7
                      name: 'accusamus est cum'
                    -
                      id: 8
                      name: 'et suscipit suscipit'
                    -
                      id: 9
                      name: 'qui veritatis est'
                    -
                      id: 10
                      name: 'non est corrupti'
                    -
                      id: 12
                      name: 'Categoria con fichero 3'
                    -
                      id: 13
                      name: 'Categoria con fichero 4'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'updated category from API'
                      -
                        id: 2
                        name: 'expedita aut quos'
                      -
                        id: 3
                        name: 'voluptas corporis nihil'
                      -
                        id: 4
                        name: 'eum eius velit'
                      -
                        id: 5
                        name: 'impedit maxime aliquam'
                      -
                        id: 6
                        name: 'vel voluptatibus odio'
                      -
                        id: 7
                        name: 'accusamus est cum'
                      -
                        id: 8
                        name: 'et suscipit suscipit'
                      -
                        id: 9
                        name: 'qui veritatis est'
                      -
                        id: 10
                        name: 'non est corrupti'
                      -
                        id: 12
                        name: 'Categoria con fichero 3'
                      -
                        id: 13
                        name: 'Categoria con fichero 4'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'updated category from API'
      tags:
        - Endpoints
      security: []
  /api/categories:
    get:
      summary: ''
      operationId: getApiCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiCategories
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: vitae
                  nullable: false
              required:
                - name
      security: []
  '/api/categories/{id}':
    get:
      summary: ''
      operationId: getApiCategoriesId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: alias
                  nullable: false
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
